### ISSUE TITLE
Can't search or download bundles

### ISSUE THREAD

**Issue by sequencer** [VundleVim/Vundle.vim#669] opened 2015-11-11 16:01 UTC
When I use
:BundleSearch matlab

I will receive these errors.

Error detected while processing function vundle#scripts#complete[6]..<SNR>19_load_scripts:
line    7:
E15: Invalid expression: 
E15: Invalid expression: 
Error detected while processing function vundle#scripts#complete:
line    6:
E714: List required
</error>

System
Macbook Air 2013 10.11.1
Working in China, Use shadowsocks(global) to connect.
Vim version:version 7.4.898 by Bram Moolenaar et al.(installed from brew)

Thank you!

**Comment by noscripter** [comment] 2015-12-28 16:26
#599

**Comment by nfischer** [comment] 2015-12-29 00:34
This should be good to close now, since I believe the `:PluginSearch` issues are resolved. @sequencer, can you confirm that the issue is fixed with the latest version of Vundle?

**Comment by nfischer** [comment] 2016-03-08 21:03
@ryanoasis This is also a duplicate

**Comment by ryanoasis** [comment] 2016-03-08 21:50
Thanks. closing. `:PluginSearch` works for me as well

**Closed by ryanoasis** 2016-03-08 21:50 UTC
